# Generated by Django 3.0.7 on 2020-06-12 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_tasks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.CharField(max_length=30)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Task')),
            ],
        ),
    ]
