# Generated by Django 3.0.7 on 2020-06-13 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='sites_id',
            new_name='sites',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='whitelist',
            old_name='project_id',
            new_name='project',
        ),
    ]
