# Generated by Django 3.0.7 on 2020-06-14 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200613_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.RemoveField(
            model_name='whitelist',
            name='project',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='WhiteList',
        ),
    ]
